### ISSUE TITLE
Recv nonce and sequence number are reversed

### ISSUE THREAD

**Issue by djwatson** [fridex/af_ktls#30]
For recv, aead_request_set_crypt takes the nonce, and make_aad should take the iv_recv sequence number.  These are allowed to be the same by the spec, and the current implementation does (and I guess gnutls must also?), but openssl does not, so recv doesn't work when receiving data from openssl.

**Comment by nmav** [comment]
Hi Dave, not sure I understand what is the issue. Could you pinpoint the decoding part you are referring to? Is it for DTLS (there the sequence number and the nonce are explicitly included in the packet).

**Comment by fridex** [comment]
I think that it is related to ```aead_request_set_crypt()``` where should be propagated nonce explicit from the record:
https://github.com/fridex/af_ktls/blob/master/af_ktls.c#L924
